### ISSUE TITLE
Help Tom make search.criticalzone.org more usable and appealing.

### ISSUE THREAD

**Issue by SRGDamia1** [BiG-CZ/BiG-CZ-Central#5]
In order for visitors to find what they need and enjoy the experience,  the site needs quite a bit more work on functionality and aesthetics

**Comment by SRGDamia1** [comment]
Although it's nice to see such snappy search results and faceted navigation, we do have some ways to go before the site is usable and appealing.   Some important functionality and content is inconsistent, confusing, or broken at the moment.  You are probably aware of most of these issues, but it seems worth spelling them out so that we can prioritize, brainstorm solutions, and assign tasks to specific folks.  For example, we need to explore ideas for better formatting of the Description/Abstract - adding returns, bolding, etc. And explore how easy it is to show different fields in the expanded/detailed views for a single record.

Some observations and initial ideas: 
- DESCRIPTIONS ARE HARD TO READ
  The Descriptions/abstracts for the CMS entries are hard to read. We need to explore ideas.  Maybe find ways for better formatting of the Description/Abstract field - adding returns, bolding, etc.  Or maybe shortening the Description/Abstract field and putting additional content elsewhere in XML?
- "OPEN" LINK IS BROKEN
  The "Open" link for each record is not working yet.
- JSON IS INCOMPLETE
  The JSON version of metadata is missing most of the ISO content
- METADATA ARE NOT DISPLAYED FOR NON-CMS RECORDS
  Some/all? of the non-CMS records have no visible description or other fields upon selection, despite those fields being in the dublin core metadata.  
- SOME DISPLAYED FIELDS ARE MISSING CONTENT OR SHOW INCOMPLETE CONTENT
  Date Published and Creator fields often display "Not available".  Constraints field only shows the last of three constraints. Instead of Date Published, we probably just want to show different fields such as Entry Date and Edit Date.  For Constraints, we want to either concatenate content in the XML or pull more content into the Geoportal view.  How hard is it to show other fields in Geoportal?
- OPEN TOPOGRAPHY FACET NEEDS DELETED
  We need to delete the Open topography facet for Observatories
- PROJECT LINK SHOULD BE CONSISTENT
  In the upper right, the " A project of the …" link should consistently say "Critical Zone Observatories", not "Critical Zone Observatories - Search Portal" like it does on the Home page or "Critical Zone Observatory Project" like it does on the About page. 
- DISCIPLINE FACETS NOT SO HELPFUL WHEN SUBDIVIDED?
  I personally don't find it helpful to show 2-3 "Biology Data" facets separated from 8+ "Earth Science Data" facets.  But I might be the odd one out.  We need to check with a handful of users and get their feedback.
- FACETS COULD BE INCREASED?
  Although we've talked about how long lists of facets can be hard to work with, let's actually try some out (ie Topic and Field Area).  It could work pretty well, given that many folks are likely to click an observatory or a discipline first - which will often drastically shorten the list. And the long lists could be put at the bottom.  One interface issue is that an text search - unlike a facet-only search - currently displays all facets even if they have zero results. Can we change that behavior?  Can we always remove facets that have zero results?  Or maybe just for the long-listed facets?  It's probably not critical, as text-first search would still work OK.  Worth pondering though.
- DATA CONSISTENCY NEEDS HELP
  All datasets should at least have the observatories facet and ideally disciplines too.  Are there any automated ways we can assign at least observatory to the non-CMS records?  And think about long-term plans for triggering harvesting of non-CMS datasets from the CMS and adding in some facets at the same time?  Or adding facets to the new versions of display files?
- LOCATION MAP NEEDS HELP
  If the behavior stays the same as the West Coast oceans website, let's title it "Map View" or similar instead of "Location". With a title of "location", I'd expected a list or map of all locations… not a blank map.  Clicking the map to select is not intuitive to me either.  I'd expected to be able to click and drag a bounding box to see the records within that box.  For me, a better interface would be small static map that starts by showing the locations or areas of all the relevant results.  And clicking the map would bring up a full-screen map that would allow easier zooming, subselecting, exploring etc.  And each time the search result is smaller, the map would update to show the new locations.  If we can't make at least a few improvements, we might want to delete it entirely.
- CONTENT OF "ABOUT" PAGE AND OTHER STATIC PAGES NEEDS WORK 
  We clearly need to spend time on the "static" informational pages.  Who is the audience? What do they need? What are our communication goals?  What pages and page titles make sense? Does 'Discover | Connect | Inform | About' work well for CZO? We probably want to at least change "Inform" to "Understand" or similar. One key issue is to clearly explain how this data resource differs from others, most especially the CMS datasets…. and clearly link to those resources.  We also need to explain how the text search works.  For example, searching on two words like 'ground water' is different than quoting the phrase "ground water".  Is there any way to do "and" or "or" searches?
- HOME PAGE OPTIONS AND CONTENT NEEDS MORE CONSIDERATION
  What _are_ the 4 most common or most important searches to try out? And if "groundwater" is one of them, how do we handle 'groundwater' vs 'ground water' vs "ground water"?  All four options should consistently have labels that end with "Data", ie "Groundwater Data".  The welcome message should probably give more hints about what a Critical Zone is. 
- VISUAL DESIGN NEEDS WORK
  We need a color scheme that better matches the CZO schemes better and won't be mistaken for the original West Coast Oceans. Ditto for CZO logo.  Let's also pick mages on home page that show a range of environments and sample types. And let's explore using web fonts that match or better match CZO.

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by SRGDamia1** [comment]
Oops, I'd meant to "at https://app.asana.com/0/15829753551253/15829753551253 " at the start of that last long comment.  I'm sending another comment just to make sure Tom gets an email.

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by SRGDamia1** [comment]
https://app.asana.com/0/15829753551253/15829753551253 , are you using git at all for search.criticalzone.org?  If so, maybe I can peek around at the code and files (including angular, jeykll) ?  Maybe make some changes for visual design myself?

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by SRGDamia1** [comment]
As noted in an earlier comment for this task, it's worth trying out some longer-listed facets.  They might just work with this interface after all.  

One consideration is how well we can apply the facets to all records.  Particularly tricky might be the non-CMS metadata, harvested or entered by other means at present.

We might want to try this list of options on the left rail:
Search Keywords
Map Locations (if we get it working ok)
Observatories
Disciplines
Topics
Field Areas
Start/End Dates

TOPICS
We should try Topics, especially because we already have a semi-controlled list of "Topics" and use them as a "Sort By" view in the CMS as well as dataset search results.

FIELD AREAS
We should try Topics, especially because we already have a semi-controlled list of "Topics" and use them as a "Sort By" view in the CMS as well as dataset search results.

START AND END DATE YEAR
As we talk about in the meeting on 11 Sept 2014, it would be helpful to be able to filter somehow by year, Start Date and/or End date.  Maybe a way to select start and end years?

---

OTHER FACETS?

---

Additional facets require more consideration and adding them as new fields to the CMS datasets.  They include:

VERTICAL EXTENT
There is an ISO 19115 element for this. Maybe we could add max and min elevation fields to CMS datasets much like we do for field area?

SITE TYPE
SiteType, which is a ODM2 CV that we are developing (includes sampling feature?)
Landscape?  Need a controlled list

SAMPLED MEDIUM
Sampled Medium, which is a ODM2 CV that we are developing

DATA QUALITY
Data Quality/Processing Level (raw, cleaned, gap-filled, smoothed, …)

CZEN SITE SEEKER CATEGORIES
Currently they are optional attributes to CriticalZone.org “Field Areas” and would need to add them as attributes to Datasets:
Lithology
Soil type
Biome
Landuse

PRECIPITATION
Approx mean annual precipitation mm/yr.  this is an optional field for "field areas". We would need to add it as a new field/atttribute to Datasets.

TEMPERATURE
Approx mean annual temperature C
this is an optional field for "field areas". We would need to add it as a new field/atttribute to Datasets.

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by SRGDamia1** [comment]
I'm moving this task to a lower priority, P2.  The notes for this task capture a number of ideas, but they really are meant for a longer term followup project.  These ideas need to combined with those of other folks, put into context and prioritized.  For example, the one really clear need is to have a decent spatial, geographic based search.  Which is ironic, given that this is a "geoportal".  Further discussion can happen via github issues.

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by SRGDamia1** [comment]
Actually, I'm moving it to even lower priority "possible future tasks"

[--- Commented from Asana.com
#commenter David Lubinski
---[aa]

**Comment by dlubinski** [comment]
@SRGDamia1 Hmmm... I'm a bit confused why this issue is listed under BiG-CZ and not CZOData.  Seems like it should be in the latter, if not both?
